version: 0.1.0.{build}
image: Visual Studio 2017
configuration: Release

platform:
  - Win32
  - x64

clone_folder: c:\projects\cwalk

init:
  - cmd: set arch_str=
  - cmd: if "%PLATFORM%"=="x64" (set arch_str= Win64)
  - cmd: echo %PLATFORM%
  - cmd: echo %APPVEYOR_BUILD_WORKER_IMAGE%
  - cmd: if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set GENERATOR="Visual Studio 15 2017%arch_str%" )
  - cmd: if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set GENERATOR="Visual Studio 14 2015%arch_str%" )
  - cmd: if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" ( set GENERATOR="Visual Studio 12 2013%arch_str%" )
  - cmd: echo %GENERATOR%

before_build:
  - cmd: mkdir build.win && cd build.win && cmake --version && cmake .. -DENABLE_TESTS=1 -G %GENERATOR%

build:
  project: c:\projects\cwalk\build.win\cwalk.sln
  verbosity: minimal

test_script:
  - cmd: c:\projects\cwalk\build.win\Release\cwalktest.exe
